# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aMO9zYsH3u-IfRd5KJfQRFxTQv7lQ5Bx
"""




# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import requests
# import matplotlib.pyplot as plt
# import io
# 
# st.set_page_config(page_title="GreenOpt AI", layout="centered")
# st.title("GreenOpt AI: Solar Layout Optimizer (India)")
# st.markdown("### Get 20%+ more output — *no hardware needed*")
# 
# col1, col2 = st.columns(2)
# with col1:
#     lat = st.number_input("Latitude (e.g., 26.91 for Jaipur)", value=26.91, step=0.01)
#     num_panels = st.number_input("Number of Panels", value=20, min_value=1)
# with col2:
#     lon = st.number_input("Longitude (e.g., 75.78 for Jaipur)", value=75.78, step=0.01)
#     panel_watts = st.number_input("Panel Wattage (e.g., 550W)", value=550, min_value=100)
# 
# st.info("Get Lat/Long: Right-click on Google Maps → 'What's here?'")
# 
# if st.button("Optimize Layout & Generate Report", type="primary"):
#     with st.spinner("Running AI optimization..."):
#         try:
#             capacity_kw = (num_panels * panel_watts) / 1000
#             url = f"https://developer.nrel.gov/api/pvwatts/v8.json?api_key=DEMO_KEY&lat={lat}&lon={lon}&system_capacity={capacity_kw}&azimuth=180&tilt=25&module_type=0&losses=14"
#             data = requests.get(url).json()
#             if 'errors' not in data:
#                 annual_kwh = data['outputs']['ac_annual']
#                 st.success(f"Estimated Annual Output: {annual_kwh:,.0f} kWh")
#                 st.info("Boost vs flat: ~20% (NREL standard)")
# 
#                 fig, ax = plt.subplots()
#                 ax.bar(['Your System'], [annual_kwh], color='#10a674')
#                 ax.set_ylabel("kWh/year")
#                 ax.set_title("Your Solar Output")
#                 st.pyplot(fig)
# 
#                 buffer = io.BytesIO()
#                 fig2, ax2 = plt.subplots()
#                 ax2.bar(['Optimized'], [annual_kwh], color='#10a674')
#                 ax2.set_title("GreenOpt AI Report")
#                 ax2.text(0.5, annual_kwh * 0.8, f"{annual_kwh:,.0f} kWh/year", ha='center', fontsize=12)
#                 plt.savefig(buffer, format='pdf', bbox_inches='tight')
#                 plt.close(fig2)
#                 buffer.seek(0)
#                 st.download_button("Download Report (PDF)", buffer, "GreenOpt_Report.pdf", "application/pdf")
#             else:
#                 st.error("Invalid location.")
#         except:
#             st.error("Check internet or coordinates.")
#




!pkill -f streamlit
!streamlit run app.py --server.port 8501 & lt --port 8501

!pip install streamlit requests matplotlib -q
!npm install -g localtunnel
!pkill -f streamlit
!streamlit run app.py --server.port 8501 & lt --port 8501

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import requests
# import matplotlib.pyplot as plt
# import io
# 
# st.set_page_config(page_title="GreenOpt AI", layout="centered")
# st.title("GreenOpt AI: Solar Layout Optimizer (India)")
# st.markdown("### Get 20%+ more output — *no hardware needed*")
# 
# col1, col2 = st.columns(2)
# with col1:
#     lat = st.number_input("Latitude (e.g., 26.91 for Jaipur)", value=26.91, step=0.01)
#     num_panels = st.number_input("Number of Panels", value=20, min_value=1)
# with col2:
#     lon = st.number_input("Longitude (e.g., 75.78 for Jaipur)", value=75.78, step=0.01)
#     panel_watts = st.number_input("Panel Wattage (e.g., 550W)", value=550, min_value=100)
# 
# st.info("Get Lat/Long: Right-click on Google Maps → 'What's here?'")
# 
# if st.button("Optimize Layout & Generate Report", type="primary"):
#     with st.spinner("Running AI optimization..."):
#         try:
#             capacity_kw = (num_panels * panel_watts) / 1000
#             url = f"https://developer.nrel.gov/api/pvwatts/v8.json?api_key=DEMO_KEY&lat={lat}&lon={lon}&system_capacity={capacity_kw}&azimuth=180&tilt=25&module_type=0&losses=14"
#             data = requests.get(url).json()
#             if 'errors' not in data:
#                 annual_kwh = data['outputs']['ac_annual']
#                 st.success(f"Estimated Annual Output: {annual_kwh:,.0f} kWh")
#                 st.info("Boost vs flat: ~20% (NREL standard)")
# 
#                 fig, ax = plt.subplots()
#                 ax.bar(['Your System'], [annual_kwh], color='#10a674')
#                 ax.set_ylabel("kWh/year")
#                 ax.set_title("Your Solar Output")
#                 st.pyplot(fig)
# 
#                 buffer = io.BytesIO()
#                 fig2, ax2 = plt.subplots()
#                 ax2.bar(['Optimized'], [annual_kwh], color='#10a674')
#                 ax2.set_title("GreenOpt AI Report")
#                 ax2.text(0.5, annual_kwh * 0.8, f"{annual_kwh:,.0f} kWh/year", ha='center', fontsize=12)
#                 plt.savefig(buffer, format='pdf', bbox_inches='tight')
#                 plt.close(fig2)
#                 buffer.seek(0)
#                 st.download_button("Download Report (PDF)", buffer, "GreenOpt_Report.pdf", "application/pdf")
#             else:
#                 st.error("Invalid location.")
#         except:
#             st.error("Check internet or coordinates.")

!pip install streamlit requests matplotlib -q
!npm install -g localtunnel
!pkill -f streamlit
!streamlit run app.py --server.port 8501 & lt --port 8501
